# -*- coding: utf-8 -*-
"""Cardiode

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1thY82Zr53n4i92wwCKoidlIYFnTr4JYN
"""

import matplotlib.pyplot as plt
from matplotlib.pyplot import figure
import numpy as np
import math

"""## Linea"""

#figure = definir el tamaño del grafico
figure(figsize=(10,8), dpi=80)
valores = [10,20]
angulos = [np.pi,np.pi/2]
plt.polar(angulos, valores, c='r')

"""## Circulo"""

plt.axes(projection = 'polar')

r = 2

rads = np.arange(0,(2 * np.pi), 0.01)

for rad in rads:
  plt.polar(rad, r, 'g.')

plt.show()

"""## Elipse

$$r = \frac{a*b}{\sqrt{(a*sin(\theta ))^{2} + (b*cos(\theta ){^{2}})}}$$
"""

plt.axes(projection = 'polar')

a = 4
b = 3

rads = np.arange(0,(2 * np.pi), 0.01)

for rad in rads:
    r = (a*b)/math.sqrt((a*np.sin(rad))**2 + (b*np.cos(rad))**2)
    plt.polar(rad, r, 'g.')

plt.show()

"""## Cardioide

$$r = a*cos(\theta )$$
"""

plt.axes(projection = 'polar')

a = 4

rads = np.arange(0,(2 * np.pi), 0.01)

for rad in rads:
    r = a + (a*np.cos(rad))
    plt.polar(rad, r, 'g.')

plt.show()